version: '3.6'
services:
  tech-hub-api:
    container_name: tech-hub-backend
    build: ./
    command: npm start
    volumes:
      - ./:/Users/dayanperera/Documents/Udemy/tech-developer-hub
    ports:
      - "5000:5000"
    links: 
      - "mongodatabase"
    depends_on:
          - "mongodatabase"
  mongodatabase:
    container_name: tech-hub-db
    image: "mongo:3.2.20"
    volumes:
      - ./data/:/data/db
    ports:
      - "27017:27017"


      

