version: '3.6'
services:
  backend-api:
    container_name: tech-hub-backend
    build: ./
    command: npm start
    volumes:
      - ./:/Users/dayanperera/Documents/Udemy/tech-developer-hub
    ports:
      - "5000:5000"
    links: 
      - "mongodatabase"
    depends_on:
          - "mongodatabase"
  mongodatabase:
    container_name: techhubdb
    image: "mongo"
    ports:
      - "27017:27017"


      

